version: "3"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: metadata
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"